### ISSUE TITLE
Can't find name Cryptostacking in validator search box

### ISSUE THREAD

**Issue by m4dh** [itering/subscan-issue-tracker#10]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Kusama

### Steps to reproduce

1. open site https://kusama.subscan.io/validator
2. in a search validator box i type cryptostacking or CryptoStacking
3. i can't find that validator
4. i can find that validator by sorting list of validators ....

### Expected output

possibility to find a searched name

### Actual output

none

**Comment by carlhong** [comment]
@m4dh  Can you provide the account link to cryptostacking?

**Comment by m4dh** [comment]
sure @carlhong 
https://kusama.subscan.io/account/DfMNYNmnY8bDbWujGrGnxk466bnYZLDvkdgDcnEPCQ12hFx

**Comment by carlhong** [comment]
@m4dh It should be fixed now.
