### ISSUE TITLE
Incorrect Price Data from Latest Polkadot Blocks (8434725)

### ISSUE THREAD

**Issue by shawntabrizi** [itering/subscan-issue-tracker#11]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Polkadot

### Steps to reproduce

```
curl -X POST 'https://polkadot.api.subscan.io/api/open/price' \
  --header 'Content-Type: application/json' \
  --header 'X-API-Key: YOUR_KEY' \
  --data-raw '{
    "time": 8434725
  }'
```

### Expected output

The current price of Polkadot.

### Actual output

```
{"code":0,"message":"Success","generated_at":1641355263,"data":{"price":"0.0415348226","time":1641313140,"height":8434751,"records":[{"price":"0.0415348226","height":8434751,"time":1641313140},{"price":"60.0883978891","height":8434705,"time":1641312840}]}}
```

**Comment by freehere107** [comment]
@shawntabrizi Thank you for feedback, I noticed some changes in the price API of CMC, today I will repair the data

**Comment by freehere107** [comment]
@shawntabrizi This issue has been fixed
