### ISSUE TITLE
Transaction failed due Existential Deposit

### ISSUE THREAD

**Issue by olaitantm** [itering/subscan-issue-tracker#13]
https://polkadot.subscan.io/extrinsic/0xfbf4bb846f38e50c4ba7a5d019c23b74e0781a33d0a32dd6076efdaccf72d533

Can I know the reason and can I have a refund?

**Comment by yakio** [comment]
![image](https://user-images.githubusercontent.com/46353690/149261052-9fcc107b-805a-404d-93e6-413f3cecb09c.png)
![image](https://user-images.githubusercontent.com/46353690/149261422-38d768c3-444a-4539-858e-ef893fb83daf.png)
Currently for polkadot network, the minimum amount required to keep an account open is 1 DOT.

**Comment by yakio** [comment]
> https://polkadot.subscan.io/extrinsic/0xfbf4bb846f38e50c4ba7a5d019c23b74e0781a33d0a32dd6076efdaccf72d533
> 
> Can I know the reason and can I have a refund?

![image](https://user-images.githubusercontent.com/46353690/149261052-9fcc107b-805a-404d-93e6-413f3cecb09c.png)
![image](https://user-images.githubusercontent.com/46353690/149261422-38d768c3-444a-4539-858e-ef893fb83daf.png)
Currently for polkadot network, the minimum amount required to keep an account open is 1 DOT.
