### ISSUE TITLE
crowdloan altair

### ISSUE THREAD

**Issue by pugarte** [itering/subscan-issue-tracker#4]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

altair kusama

### Steps to reproduce

1.- on 2021-08-31 17:37:54 (+UTC), I donated 1.046115940 KSM on staked, from this account HPCrASz6JoestJxgjUZPYqQtie4SiQLr59542jdm2h1efsU expecting a reward of 483.2520 AIR.
2.-the extrinsic hash is 0xcecd0d5dbab07252589c5ab5dcef56ce8071b405d70bc09e3b7a39c4ff76abe6, but an error shows up  in the Block 9023986.
3.- as you can see in this link “https://kusama.subscan.io/block/9023986?tab=extrinsic", there's an X in the result of extrinsic id 9023986-8.

### Expected output

I expected a reward of 483.2520 AIR.

### Actual output

 When I check my polkadot account the ALTAIR token, in the "allow use on any chain" setting, it still shows up as 0.

### Additional factoids or references

I'm hoping to get back the AIR or 1.046 KSM.
The result's error is "Call 1 failed（MemoTooLarge)"

**Comment by freehere107** [comment]
@pugarte hey, maybe you need contact with https://github.com/centrifuge

**Comment by yakio** [comment]
> ### Confirmation
> * [x]  My issue isn't already found on the issue tracker.
> * [x]  I have read the Subscan API documentation (if it seemed to be an API bug).
> 
> ### Affected Network(s)
> altair kusama
> 
> ### Steps to reproduce
> 1.- on 2021-08-31 17:37:54 (+UTC), I donated 1.046115940 KSM on staked, from this account HPCrASz6JoestJxgjUZPYqQtie4SiQLr59542jdm2h1efsU expecting a reward of 483.2520 AIR. 2.-the extrinsic hash is 0xcecd0d5dbab07252589c5ab5dcef56ce8071b405d70bc09e3b7a39c4ff76abe6, but an error shows up in the Block 9023986. 3.- as you can see in this link “https://kusama.subscan.io/block/9023986?tab=extrinsic", there's an X in the result of extrinsic id 9023986-8.
> 
> ### Expected output
> I expected a reward of 483.2520 AIR.
> 
> ### Actual output
> When I check my polkadot account the ALTAIR token, in the "allow use on any chain" setting, it still shows up as 0.
> 
> ### Additional factoids or references
> I'm hoping to get back the AIR or 1.046 KSM. The result's error is "Call 1 failed（MemoTooLarge)"
Hi @pugarte,

I double check your transaction,
- You successfully contributed 1.046 KSM, the event is:
https://kusama.subscan.io/extrinsic/0xcecd0d5dbab07252589c5ab5dcef56ce8071b405d70bc09e3b7a39c4ff76abe6?event=9023986-35
- But you entered a wrong ReferralCode, and the error is: MemoTooLarge.

The data on subscan is correct. Regarding the distribution of rewards, please contact the altair team.
