### ISSUE TITLE
The number of finalized blocks and latest block doesn't match

### ISSUE THREAD

**Issue by Kunwark** [itering/subscan-issue-tracker#5]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Rococo

### Steps to reproduce

1. Visit https://rococo.subscan.io/
2. Notice that Finalized data under Chain Data shows a different number than the latest block number under Latest Blocks.
3. Also notice that the latest blocks remain unfinalized.  
![image](https://user-images.githubusercontent.com/13748763/141113614-c91d1ea8-d42d-4cea-9d40-3ef3352ef5df.png)

### Expected output

The number of finalized block and Latest Blocks is in the same range or the number of finalized block is less than Latest Blocks. 

### Actual output

Number of finalized block is a t 136,514 and latest block is at 438,595. 

### Additional factoids or references

The rococo network was reset about a week ago and it has been working normally for about a week since the reset. The new rococo is only on block 130k or something so subscan is probably on the old genesis.

**Comment by freehere107** [comment]
@Kunwark Thank you feedback, We will reset soon

**Comment by freehere107** [comment]
@Kunwark  rococo in sync https://rococo.subscan.io/
